Update pre-commit

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -6,8 +6,10 @@
 #
 # see the README
 
+TMP_STAGING="tmp_staging"
+
 PHPCS_BIN=./vendor/squizlabs/php_codesniffer/bin/phpcs
-TMP_STAGING=".tmp_staging"
+ESLINT_BIN=./node_modules/.bin/eslint
 
 # parse config
 CONFIG_FILE=$(dirname $0)/config
@@ -30,7 +32,7 @@ else
     against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
 fi
 
-# this is the magic: 
+# this is the magic:
 # retrieve all files in staging area that are added, modified or renamed
 # but no deletions etc
 FILES=$(git diff-index --name-only --cached --diff-filter=ACMR $against -- )
@@ -78,14 +80,30 @@ do
   STAGED_FILES="$STAGED_FILES $TMP_STAGING/$FILE"
 done
 
-OUTPUT=$($PHPCS_BIN $STAGED_FILES)
-RETVAL=$?
+# Execute PHPCS
+OUTPUT1=$($PHPCS_BIN $STAGED_FILES)
+RETVAL1=$?
+
+# Execute ESLINT
+OUTPUT2=$($ESLINT_BIN --quiet --ignore-pattern '*.php' --ignore-pattern $TMP_STAGING'/public/script/js' --ignore-pattern $TMP_STAGING'/public/ckeditor' --ignore-pattern $TMP_STAGING'/public/build/script' --ignore-pattern $TMP_STAGING'/vendor' $STAGED_FILES)
+RETVAL2=$?
 
 # delete temporary copy of staging area
 rm -rf $TMP_STAGING
 
-if [ $RETVAL -ne 0 ]; then
-    echo "$OUTPUT" | less
+if [ $RETVAL1 -ne 0 ]; then
+    echo "$OUTPUT1" | less
+fi
+
+if [ $RETVAL2 -ne 0 ]; then
+    echo "$OUTPUT2" | less
+fi
+
+RETVAL=0;
+if [ $RETVAL1 -ne 0 ] || [ $RETVAL2 -ne 0 ]; then
+
+   # Failure if phpcs or eslint fails
+   RETVAL=1;
 fi
 
 exit $RETVAL
